
services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app/api
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite:////app/data/horai.db
      - GROQ_API_KEY=${GROQ_API_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3